server:
  port: 9000
spring:
  application:
    name: olx-login
  config:
    import: configserver:http://localhost:8888
  zipkin:
    base-url: http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /olx-login-monitor
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true