server:
  port: 9191

spring:
  application:
    name: olx-gateway

  cloud:
    gateway:
      routes:
        - id: OLX-LOGIN
          uri: lb://OLX-LOGIN
          predicates:
            - Path=/user/**
        - id: OLX-ADVERTISES
          uri: lb://OLX-ADVERTISES
          predicates:
            - Path=/advertise/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka